username_blank_error: "user id can not be blank"
address_blank_error: "Please enter Address and number"
address_to_short: "Adress too short! Must be at least 2 characters"
address_to_maximum: "Too long! Maximum 40 characters"
address_to_digit: "Address name must have some letters!"
fname_blank_error: "Please enter first name (2-40 characters)"
firstname_invalid_format: "First name can only contain letters, apostrophe or hyphen."
firstname_to_short: "Please enter first name (2-40 characters)"
firstname_to_maximum: "Too long! Maximum 40 characters"
lname_blank_error: "Please enter last name (2-40 characters)"
lastname_invalid_format: "Last name can only contain letters, apostrophe or hyphen."
lastname_to_short: "Please enter last name (2-40 characters)"
lastname_to_maximum: "Too long! Maximum 40 characters"
phone_blank_error: "Please enter home phone number (up to 15 digits)"
phone_numeric: "Phone number can only contain numbers and '+'"
phone_to_short: "Phone number too short! Must be at least 8 digits"
phone_long_error: "Too long! Maximum 15 digits"
mobile_long_error: "Too long! Maximum 15 digits"
mobile_blank_error: "Mobile Number can't be blank"
mobile_numeric_error: "Phone number can only contain numbers and '+'"
mobile_blank_error: "Mobile number can't be blank"
username_size_error: "Sorry, your username must be between 6 and 30 characters long."

username_unique_error: "Username is already taken"

password: "Password can not be blank, Password should be combination of Alphanumeric"
re-type_password: "Password mismatch"
email_blank_error: "Please enter a valid email address"
email_invalid_error: "Please enter a valid email address"
email_existing_error: "Sorry, this email address has already been used!"
registration_submit: "Congratulations! You've now set up your account."
area_code_blank: "Please enter Area code"
area_code_to_short: "Area code too short! Must be at least 2 numbers"
area_code_to_maximum: "Too long! Maximum 10 digits"
area_code_number: "Area code must be numbers"

country_id: "Please select your country"
state_id: "Please select your country"
city_id: "Please select your country"
location_id: "Please select your country"
role_id: "Please select your Role"

user_id_error: "Please enter a valid User id"
login_password_blank: "Please enter your password (6 - 32 characters)"
login_password_min: "Your password should be less than 32 characters long"
login_password_max: "Your password should be less than 32 characters long"
login_password_mismatch: "Sorry! Invalid email/password combination. Please try again."
login_success: "Yes! You've signed in to AskVee!"

forgot_reset_password: "We've sent you an email to reset your password. Please check it now!"

password_reset_success: "Password reset success."
password_reset_fail: "Password reset failed."
password_mismatch_error: "Password mismatch" 
login_fail: "Please activate your account"
signup_complete: "Thanks for signing up! We have sent you a email with your activation code. Please check your email for Activating your A/c"
signout_success: "You have been signed out."
profile_update_success: "Profile Updated"

dinner_description_empty: "Dinner description Can not be blank"
dinner_description_numeric: "Numeric value should not be accepted"
food_available_empty: "Availability Can not be blank"
dinner_name_empty: "Enter the dinner name"
dinner_price_empty: "Price details Can not be blank"
dinner_save: "Dinner name has been saved."
dinner_update: "Dinner have been updated"
dinner_delete: "Dinner have been deleted"

tour_description_empty: "Tour description Can not be blank"
tour_description_numeric: "Numeric value should not be accepted"
tour_guide_availability_error: "Availability Can not be blank"
tour_visiting_location_error: "Enter the offered location name"
tour_price_error: "Price details Can not be blank"
tour_guide_specific_error: "Tour guide can't be blank"
tour_save: "Tour guide details have been saved."

accomodation_description: "Enter the description"
accomodation_green_profile_question: "Select at least one Green Profile question"
accomodation_property_type: "Select the property type"
accomodation_rooms_available: "Availability Can not be blank"
accomodation_photo: "Photo field Can not be left blank"
accomodation_amenities: "Select at least one Amenity"
accomodation_price: "Price details Can not be blank"
accomodation_currency: "Select the currency"
accomodation_available: "Availability Can not be blank"
accomodation_property: "Select the property type"
accomodation_accommodates: "Select the no of accommodates"

search_from_date: "Date field can not be blank"
search_from_date_past: "From date should not be past date"
search_to_date: "Can not be blank"
search_date_past: "To date should not be past date"
search_check_Availability: "Availability dinner ads will get displayed"
search_request_for_reservation: "If the user has already registered a booking page will be displayed, else system will ask for registration."

calendar_update_ad: "Select ad from dropdown"
calendar_update_date: "Select the date"

