production:
  bucket : askvee
  access_key_id: AKIAI6Z2U7NDVTWIRASQ
  secret_access_key: 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
development:
  bucket : askvee-dev
  access_key_id: AKIAI6Z2U7NDVTWIRASQ
  secret_access_key: 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